### ISSUE TITLE
bl-aerosnap fails if window is undecorated

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-utilities#18]
If the active window is undecorated, then after left/right snaps the top of the window is off the screen. The script then doesn't get the window geometry and fails.

`Traceback (most recent call last):`
 `File "/home/damo/bin/bl-aerosnap", line 126, in <module>`
  `window_store()`
  `File "/home/damo/bin/bl-aerosnap", line 76, in window_store`
  `s = ID +'|'+window_geometry(ID)+'\n'`
`TypeError: cannot concatenate 'str' and 'NoneType' objects`

**Comment by Hjdskes** [comment]
@capn-damo Could you test this again with [my version](https://raw.githubusercontent.com/Unia/bunsen-utilities/master/bl-aerosnap) of the script?

Also, since I'm using XLib/EWMH directly, user defined margins should work now too - if Openbox does nothing weird in its implementation. They work in GNOME Shell at least, both with its own panel and a running tint2.

**Comment by Hjdskes** [comment]
^ Just confirmed: user defined margins work as expected now

**Comment by Hjdskes** [comment]
^^ Undecorated windows also work for me
