### ISSUE TITLE
CONKYPATH in bl-conkyzen and bl-conky-session

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-utilities#2]
atm it is `CONKYPATH="$HOME/.conky"` but presumably it should be `CONKYPATH="$HOME/.config/conky"`, to bring it into line with all the other .config applications. The default conkyrc would then be a symlink: `$HOME/.conkyrc -> $HOME/.config/conky/.conkyrc`. 

Conkys need to be in $CONKYPATH, but if the user has symlinks in `.config` to multiple conky dirs, then the conky search path needs to use `find -L "$CONKYPATH"`. This is likely to make the gui load slowly if `find` has to traverse a lot of dirs. 
Leave the choice of `find -L` to the user? Presumably if they have got that far they already know how to set up symlinks and use `find`?

I could make a pipemenu link to a help-doc, to expand on usage.

**Comment by Sector11** [comment]
But the version I put on line the was for:

```
$HOME/.config/conky
```

**Comment by capn-damo** [comment]
Good. I couldn't recall what was discussed, so I was just double-checking before I edit the scripts :)

**Comment by Sector11** [comment]
I have to reopen this.

I just used the bunsenlas-netinstall script and I see that the bunsen conkys (~/.config/conky) are being totally ignored as there is a ~/.conkyrc that is running.  It is the old #! default.

**Comment by capn-damo** [comment]
~/.conkyrc should be a symlink to ~/.config/conky/BL-default.conkyrc

Maybe it wasn't changed to a link as we decided?

**Comment by johnraff** [comment]
Indeed it wasn't. My oversight. At the time bunsen-configs was mostly being put together bunsen-conky was still in the development phase.

**Comment by johnraff** [comment]
@capn-damo just to check - the current conky scripts also handle a conky config at ~/.conkyrc so it's now OK to have a file there rather than a symlink?

See this discussion: https://github.com/BunsenLabs/bunsen-conky/issues/9 especially towards the end.

So now it looks as if **bunsen-configs** might be installing a default conky at ~/.conkyrc.

Still wavering on this one. Users who don't have **bunsen-conky** should still have a default conky file, so the question is whether it would be better to have it in the standard location, or let bunsen-configs install  the single file ~/.config/conky/BL-default.conkyrc  (and the rest by bunsen-conky) with a symlink pointing there from ~/.conkyrc, as we were thinking.

Bruce has convinced me there's a case for having a default ~/.conkyrc _as well as_ ~/.config/conky/BL-default.conkyrc as a sort of backup. What do you think @capn-damo ?

**Comment by capn-damo** [comment]
Doesn't matter to me if `~/.conkyrc` is a file or symlink. bl-conkyzen does a check for a file in that location with 
`CRC="$HOME/.conkyrc"`.....
`if [ -e "$CRC" ]`.....
 so it should work whether or not it is a symlink.

Seems that the netinstall already installs what looks like the waldorf  default `~/.conkyrc` ?

**Comment by johnraff** [comment]
A relic. I switched to symlink in my "test" branch but before merging it with "master" the later discussion came up so it stayed, in its Waldorf state. Now updated, so bunsen-configs puts in a copy of ~/.config/conky/BL-default.conkyrc at ~/.conkyrc, and all the other files (including BL-default.conkyrc) are installed by bunsen-conky.
